# Playbook para implantação e execução da DCGAN
# Você deve adicionar mais tasks a partir do local indicado, abaixo.
# Lembre-se que a indentação é muito importante.
# Para mais informações sobre YAML, veja: https://docs.ansible.com/ansible/latest/reference_appendices/YAMLSyntax.html

- name: Play para configurar e executar a DCGAN em uma máquina.
  hosts: cloud
  tasks:
  # Teste simples. A mensagem "Teste SSH OK!" deve ser impressa na tela
  - name: "Apenas testando o SSH"
    debug:
      msg: "Teste SSH OK!"

  # Task utilizada para adicionar o usuário ubuntu ao grupo Docker
  - name: "Adicionar usuario ubuntu ao grupo docker"
    become: true
    user:
      name: ubuntu
      groups: docker
      append: yes

  # Reinicia a conexão SSH
  - name: "Reinicar a conexão ssh para a alterações de grupos tenham efeito"
    ansible.builtin.meta:
      reset_connection

  ###############################################
  #   Adicione suas tasks a partir daqui..      #
  ###############################################



  ###############################################
  #   Fim das suas tasks..                      #
  ###############################################

  # Imprime uma mensagem de sucesso
  - name: "Final"
    debug:
      msg: "Playbook executado com sucesso!"
